apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: default
spec:
  serviceAccountName: prometheus
  replicas: 1
  ruleSelector:
    matchLabels:
      release: prometheus
  serviceMonitorSelector:
    matchLabels:
      release: prometheus
  spec:
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager-operated
      port: web
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
          topologyKey: kubernetes.io/hostname
  resources:
    requests:
      memory: 400Mi
